variables:
  DOCKER_HOST: tcp://192.168.10.3:2378

before_script:
  - docker info

build_image:
  script:
    - docker build -t registry.git.leon.wtf/leon/cfupdater:latest .
    - docker push registry.git.leon.wtf/leon/cfupdater:latest
    