image: docker:dind

variables:
  DOCKER_HOST: tcp://192.168.10.3:2375

before_script:
  - docker info

stages:
  - build_image
  - push_image

build_image:
  script:
    - docker build -t registry.git.leon.wtf/leon/cfupdater:latest .

push_image:
  script:
    - docker push registry.git.leon.wtf/leon/cfupdater:latest