image: docker:dind

stages:
  - build
  - push

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/leon/cfupdater:latest .

push_image:
  stage: push
  only:
    - master
  script:
    - docker push $CI_REGISTRY/leon/cfupdater:latest